### ISSUE TITLE
Staging test is not available in the Typescript version

### ISSUE THREAD

**Issue by marthendalnunes** [PatrickAlphaC/hardhat-fund-me-fcc#11]
The Typescript version has only the unit test folder. The staging test with the `FundMe.staging.test.ts` file is missing.
![image](https://user-images.githubusercontent.com/18421017/173155577-3717f50a-1e38-4fab-80a0-5600cd2c03fb.png)

**Comment by PatrickAlphaC** [comment]
Thanks! Hope someone can tackle :)

**Comment by marthendalnunes** [comment]
@PatrickAlphaC just created it 😉
