### ISSUE TITLE
MockV3Aggregator Solidity version

### ISSUE THREAD

**Issue by Sacha924** [PatrickAlphaC/hardhat-fund-me-fcc#112]
Hello,
Even If I can compile the code with "yarn hardhat compile", 
when I do "solhint 'contracts/**/*.sol" It tells me that I have one error :
![image](https://user-images.githubusercontent.com/91620859/200116728-2a8e68bd-dab1-435a-98fa-6e68501f242a.png)

Would it be better to use ^0.8.7 solidity version avec the v0.8 MockV3Aggregator like this so we don't get any error : 

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

import "@chainlink/contracts/src/v0.8/tests/MockV3Aggregator.sol";

**Comment by PatrickAlphaC** [comment]
Mockv3aggregator.sol doesn't exist for 0.6. So you'll want to make sure your `hardhat.config.js` has `0.6.6` as one of it's compiler versions.
