### ISSUE TITLE
FundMe is not compiling and getting error

### ISSUE THREAD

**Issue by yasiriqbal1990** [PatrickAlphaC/hardhat-fund-me-fcc#12]
ParserError: Expected ';' but got '('
 --> contracts/FundMe.sol:7:15:
  |
7 | error NotOwner();
  |               ^

Error HH600: Compilation failed

**Comment by cipher222** [comment]
looks like there is an error with the code above that line. Did you forget to add a "; " at the end of import "./PriceConverter.sol";?

**Comment by yasiriqbal1990** [comment]
Here is what my code above that is looks like. there is no error. Its working perfectly on remix but on visual studio and hardhat.

import "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";
import "./PriceConverter.sol";

**Comment by PatrickAlphaC** [comment]
Need more information.

Did you run `yarn hardhat compile`? 

And could you make this a question on the main repo?  https://github.com/smartcontractkit/full-blockchain-solidity-course-js
