### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by vickyeswar** [PatrickAlphaC/hardhat-fund-me-fcc#126]
was trying to deploy contract in hardhat local network after creating mock.js but got this error.

00-deploy-mocks.js Code : 
const { network } = require("hardhat")
const { DECIMALS, INITIAL_ANSWER } = require("../helper-hardhat-config")

module.exports = async ({ getNamedAccounts, deployments }) => {
    const { deploy, log } = deployments
    const { deployer } = await getNamedAccounts()
    const chainid = network.config.chainId

    if (chainid == 31337) {
        log("Local network  detected! Deploying Mocks...")
        await deploy("MockV3Aggregator", {
            contract: "MockV3Aggregator",
            from: deployer,
            log: true,
            args: [DECIMALS, INITIAL_ANSWER],
        })
        log("Mocks Deployed!")
        log("_________________________________________")
    }
}
module.exports.tags = ["all", "mocks"]

error i got : 

Nothing to compile
Local network  detected! Deploying Mocks...
An unexpected error occurred:

Error: ERROR processing /Documents/Solidity/Hardhat Crowd Fund/deploy/00-deploy-mocks.js:
TypeError: Cannot read properties of undefined (reading 'length')

TIA

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
