### ISSUE TITLE
Why my solidity staging test couldn't finish

### ISSUE THREAD

**Issue by babelpainterwell** [PatrickAlphaC/hardhat-fund-me-fcc#129]
Here 's more details on my code:

https://ethereum.stackexchange.com/q/142091/114274

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
