### ISSUE TITLE
 Error: transaction failed

### ISSUE THREAD

**Issue by hashim715** [PatrickAlphaC/hardhat-fund-me-fcc#140]
![Screenshot 2023-02-03 174731](https://user-images.githubusercontent.com/60181698/216607243-01f159f4-1228-4b1b-951a-dea554194810.png)
I am receiving this error during staging test on a real test network goerli.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
