### ISSUE TITLE
FRONTEND WITHDRAW FUNCTION [VIDEO 13hr-38min ]getBalance still high after withdrawal

### ISSUE THREAD

**Issue by ogbambam365** [PatrickAlphaC/hardhat-fund-me-fcc#143]
![Screenshot (88)](https://user-images.githubusercontent.com/121587038/218341706-1fa35683-cc58-4747-bca2-5eb8c718a04d.png)
eth value still present after withdrawal ....please help with suggestions .

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
