### ISSUE TITLE
JsonRpcProvider error

### ISSUE THREAD

**Issue by arkhidr** [PatrickAlphaC/hardhat-fund-me-fcc#153]
FundMe
    constructor
      1) "before each" hook for "sets the aggregator addresses correctly"

  0 passing (1s)
  1 failing

  1) FundMe
       "before each" hook for "sets the aggregator addresses correctly":
     TypeError: Cannot read properties of undefined (reading 'JsonRpcProvider')

Thats was the error thrown when testing the contract
i tried the following answer and worked for me, i submitted the link bellow for the reference.

> https://ethereum.stackexchange.com/questions/144451/typeerror-cannot-read-properties-of-undefined-reading-jsonrpcprovider

Regards.

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
