### ISSUE TITLE
module.export.tags 

### ISSUE THREAD

**Issue by muhammet72** [PatrickAlphaC/hardhat-fund-me-fcc#159]
module.exports.tags does not work 

---------------
yarn hardhat deploy --tags mocks
yarn run v1.22.15
$ /home/code/hardhat-fund-me/node_modules/.bin/hardhat deploy --tags mocks
Nothing to compile
An unexpected error occurred:

Error: ERROR processing skip func of /home/code/hardhat-fund-me/deploy/01-deploy-fund-me.js:
ReferenceError: chainId is not defined
    at Object.<anonymous> (/home/code/hardhat-fund-me/deploy/01-deploy-fund-me.js:4:46)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at DeploymentsManager.executeDeployScripts (/home/code/hardhat-fund-me/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1093:22)
    at DeploymentsManager.runDeploy (/home/code/hardhat-fund-me/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:16)
    at SimpleTaskDefinition.action (/home/code/hardhat-fund-me/node_modules/hardhat-deploy/src/index.ts:438:5)
    at DeploymentsManager.executeDeployScripts (/home/code/hardhat-fund-me/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1100:15)
    at DeploymentsManager.runDeploy (/home/code/hardhat-fund-me/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:16)
    at SimpleTaskDefinition.action (/home/code/hardhat-fund-me/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/home/code/hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at Environment.run (/home/code/hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
    at SimpleTaskDefinition.action (/home/code/hardhat-fund-me/node_modules/hardhat-deploy/src/index.ts:584:32)
    at Environment._runTaskDefinition (/home/code/hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at Environment.run (/home/code/hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
    at SimpleTaskDefinition.action (/home/code/hardhat-fund-me/node_modules/hardhat-deploy/src/index.ts:669:5)
    at Environment._runTaskDefinition (/home/code/hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by cryptocambi** [comment]
Hi Mohammet72,

Yes I did:

require("@nomiclabs/hardhat-waffle")
require("hardhat-gas-reporter")
require("@nomiclabs/hardhat-etherscan")
require("dotenv").config()
require("solidity-coverage")
require("hardhat-deploy")
// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more
/**
 * @type import('hardhat/config').HardhatUserConfig
 */

const COINMARKETCAP_API_KEY = process.env.COINMARKETCAP_API_KEY || ""
const SEPOLIA_RPC_URL =
    process.env.SEPOLIA_RPC_URL ||
    "https://eth-sepolia.g.alchemy.com/v2/YOUR-API-KEY"
const PRIVATE_KEY =
    process.env.PRIVATE_KEY ||
    "0x11ee3108a03081fe260ecdc106554d09d9d1209bcafd46942b10e02943effc4a"
const ETHERSCAN_API_KEY = process.env.ETHERSCAN_API_KEY || ""

module.exports = {
    defaultNetwork: "hardhat",
    networks: {
        hardhat: {
            chainId: 31337,
            // gasPrice: 130000000000,
        },
        sepolia: {
            url: SEPOLIA_RPC_URL,
            accounts: [PRIVATE_KEY],
            chainId: 11155111,
            blockConfirmations: 6,
        },
    },
    solidity: {
        compilers: [
            {
                version: "0.8.7",
            },
            {
                version: "0.6.6",
            },
        ],
    },
    etherscan: {
        apiKey: ETHERSCAN_API_KEY,
        // customChains: [], // uncomment this line if you are getting a TypeError: customChains is not iterable
    },
    gasReporter: {
        enabled: true,
        currency: "USD",
        outputFile: "gas-report.txt",
        noColors: true,
        // coinmarketcap: COINMARKETCAP_API_KEY,
    },
    namedAccounts: {
        deployer: {
            default: 0, // here this will by default take the first account as deployer
            1: 0, // similarly on mainnet it will take the first account as deployer. Note though that depending on how hardhat network are configured, the account 0 on one network can be different than on another
        },
    },
    mocha: {
        timeout: 500000,
    },
}

when I run the command "yarn hardhat", this is what appear:

Hardhat version 2.14.0

Usage: hardhat [GLOBAL OPTIONS] <TASK> [TASK OPTIONS]

GLOBAL OPTIONS:

  --config              A Hardhat config file.
  --emoji               Use emoji in messages.
  --flamegraph          Generate a flamegraph of your Hardhat tasks
  --help                Shows this message, or a task's help if its name is provided
  --max-memory          The maximum amount of memory that Hardhat can use.
  --network             The network to connect to.
  --show-stack-traces   Show stack traces (always enabled on CI servers).
  --tsconfig            A TypeScript config file.
  --typecheck           Enable TypeScript type-checking of your scripts/tests
  --verbose             Enables Hardhat verbose logging
  --version             Shows hardhat's version.


AVAILABLE TASKS:

  check                                         Check whatever you need
  clean                                         Clears the cache and deletes all artifacts
  compile                                       Compiles the entire project, building all artifacts
  compile:solidity:get-compilation-job-for-file
  compile:solidity:get-compiler-input
  console                                       Opens a hardhat console
  coverage                                      Generates a code coverage report for tests
  flatten                                       Flattens and prints contracts and their dependencies. If no file is passed, all the contracts in the project will be flattened.
  help                                          Prints this message
  node                                          Starts a JSON-RPC server on top of Hardhat Network
  run                                           Runs a user-defined script after compiling the project
  test                                          Runs mocha tests
  typechain                                     Generate Typechain typings for compiled contracts
  verify                                        Verifies contract on Etherscan

To get help for a specific task run: npx hardhat help [task]

Done in 2.05s.


I am thinking to add it manually on "hardhat.config.js", I don't know how to do it and where to find materials to learn how to  do it.

**Comment by GIRISHNP** [comment]
@PatrickAlphaC  
"Sorry to bother u"
yarn hardhat deploy --tags mocks 
It gives 'Nothing to compile' 

here is the code
'const { developmentChains, DECIMALS, INITIAL_ANSWER } = require("../helper-hardhat-config")
const { network } = require("hardhat");
module.exports = async ({ getNamedAcoounts, deployments }) => {
    const { deploy, log } = deployments
    const { deployer } = await getNamedAcoounts()
    const chainId = network.config.chainId
    console.log(network.name);

    if (chainId == 31337) {
        log("Local network detected ! Deploying mocks .... ")
        await deploy("MockV3Aggregator", {
            contract: "MockV3Aggregator",
            from: deployer,
            log: true,
            args: [DECIMALS, INITIAL_ANSWER]
        })
        log("Mock deployed !")
        log("-------------------------------------------")
    }

}
module.exports.tags = ["all", "mocks"]'

**Comment by GIRISHNP** [comment]
version 6 in MockV3Aggregator.sol its no longer working iam using version that may be the issue or mocks,tags  are not working in that verion anymore,
//Iam thinking to go with next lesson , I got frustrated to solving this issue

**Comment by GIRISHNP** [comment]
How many lessons do you completed bro

**Comment by cryptocambi** [comment]
At the moment I am working on the Lottery contract, lesson 9. I did finish
the Simple storage contract and getting issue with  issue with the Fund me
contract.
What version of the MocksV3Aggregator are you using?

**Comment by cryptocambi** [comment]
My man,

I managed to compile and deploy the fund me contract.
I followed this link explanation:
https://hardhat.org/hardhat-runner/docs/guides/compile-contracts
I basically clean the case and compiled and after deployed, it works.

Its really frustrating when you understand why is not working, but when you
get it the amount of knowledge you acquire is pure dopamine :).

By the way, where are you based?

**Comment by GIRISHNP** [comment]
I used all the versions, still it won't work ..., I removed module.export
and tried to run  specific file (00-fund-me.js) it doesn't work ,  no
anonymous func is calling itself ..,
Can I get yr IG or mail-id , linked in  to have touch with  you , if i got
stuck in any problem we can discuss, vice versa

**Comment by cryptocambi** [comment]
yes, of course. On IG look for @cryptocambi

I notice spelling mistake on the contract that you paste, you wrote "
getNamedAcoount" instead than "getNamedAccounts"
Actually depend how you wrote it when you defined on your hardhat.config.js
file

**Comment by PatrickAlphaC** [comment]
Nice work together :)

**Comment by GIRISHNP** [comment]
Hey bro its been 3 days that I sent u a message in insta u r not
responding, stay active there

**Comment by PatrickAlphaC** [comment]
@GIRISHNP they are helping out of the goodness of their heart. Please don't abuse that. Sometimes people won't be able to get back to you.

**Comment by cryptocambi** [comment]
Hi Girish,

I am having this issue "Lesson 9 Error: "before each" hook for "initializes
the raffle correctly": #1714"
The solution if to pull a request and merge it. But I think I am missing
something in the process.
check attachment

thank bro

**Comment by cryptocambi** [comment]
Hi Girish,

I have just tested my raffle mock deploy contract, it works. Here if you
want to compare it:

const { developmentChains } = require("../helper-hardhat-config")
const { ethers } = require("hardhat")

const BASE_FEE = ethers.utils.parseEther("0.25")
const GAS_PRICE_LINK = 1e9

module.exports = async function ({ getNamedAccounts, deployments }) {
    const { deploy, log } = deployments
    const { deployer } = await getNamedAccounts()
    const chainId = network.config.chainId
    const args = [BASE_FEE, GAS_PRICE_LINK]

    if (chainId == 31337) {
        log("Local network detected: Deeploying mocks....")

        await deploy("VRFCoordinatorV2Mock", {
            from: deployer,
            log: true,
            args: args,
        })

        log("Mock deployed!")
        log("----------------------------------------")
    }
}
module.exports.tags = ["all", "mocks"]

the command that I use to deploy it is :

yarn hardhat deploy --tags deploy-mock.js

**Comment by cryptocambi** [comment]
Hi,
this my fund me  deploy mock contract:
const { developmentChains } = require("../helper-hardhat-config")
const { ethers } = require("hardhat")

const BASE_FEE = ethers.utils.parseEther("0.25")
const GAS_PRICE_LINK = 1e9

module.exports = async function ({ getNamedAccounts, deployments }) {
    const { deploy, log } = deployments
    const { deployer } = await getNamedAccounts()
    const chainId = network.config.chainId
    const args = [BASE_FEE, GAS_PRICE_LINK]

    if (chainId == 31337) {
        log("Local network detected: Deeploying mocks....")

        await deploy("VRFCoordinatorV2Mock", {
            from: deployer,
            log: true,
            args: args,
        })

        log("Mock deployed!")
        log("----------------------------------------")
    }
}
module.exports.tags = ["all", "mocks"]


keep me update pls

**Comment by cryptocambi** [comment]
Hi Bro,
 this is the staging test :

const { developmentChains, networkConfig } =
require("../../helper-hardhat-config")
const { getNamedAccounts, deployments, ethers, network } =
require("hardhat")
const { assert, expect } = require("chai")

developmentChains.includes(network.name)
    ? describe.skip
    : describe("Raffle unit test", function () {
          let raffle, raffleEntranceFee, deployer

          beforeEach(async function () {
              deployer = (await getNamedAccounts()).deployer
              raffle = await ethers.getContract("Raffle", deployer)
              raffleEntranceFee = await raffle.getEntranceFee()
          })

          describe("FulfillRandomWord", function () {
              it("works with live chainlink keepers and Chainlink VRF, we
get a random winner", async () => {
                  const startingTimeStamp = await raffle.getLastTimeStamp()
                  const accounts = await ethers.getSigners()

                  console.log("Entering Raffle...")
                  const tx = await raffle.enterRaffle({ value:
raffleEntranceFee })
                  const txReceipt = await tx.wait(1)
                  console.log("Ok, time to wait...")
                  const winnerStartingBalance = await
accounts[0].getBalance()

                  await new Promise(async (resolve, reject) => {
                      raffle.once("WinnerPicked", async () => {
                          console.log("Winner event has been fired!")

                          try {
                              const recentWinner = await
raffle.getRecentWinner()
                              const raffleState = await
raffle.getRaffleState()
                              const winnerEndingBalance = await
accounts[0].getBalance()
                              const endingTimeStamp = await
raffle.getLastTimeStamp()

                              await
expect(raffle.getPlayer(0)).to.be.reverted
                              assert.equal(recentWinner.toString(),
accounts[0].address)
                              assert.equal(raffleState, 0)
                              assert.equal(
                                  winnerEndingBalance.toString(),

winnerStartingBalance.add(raffleEntranceFee).toString()
                              )
                              assert(endingTimeStamp > startingTimeStamp)
                              resolve()
                          } catch (error) {
                              reject(error)
                              console.log(error)
                          }
                      })
                  })
              })
          })
      })
