### ISSUE TITLE
ethers.getContract is not a function

### ISSUE THREAD

**Issue by Chidubemcodes** [PatrickAlphaC/hardhat-fund-me-fcc#16]
![Screenshot 2022-06-15 151930](https://user-images.githubusercontent.com/93622341/173942518-65313171-c1be-4681-8bfe-57076af8b21f.png)
I got this error "ethers.getContract is not a function" while running "yarn hardhat test"

**Comment by pro123908** [comment]
Can you also attach the code snippet ?

**Comment by PatrickAlphaC** [comment]
Can you please copy paste code instead of screenshot? 

Please follow this: 
https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

And can you ask in the main repo? Thank you.
