### ISSUE TITLE
error in FundMe.test.js

### ISSUE THREAD

**Issue by Sanyam2103** [PatrickAlphaC/hardhat-fund-me-fcc#160]
i am at 11:17 in the video and testing the first unit FundMe.test.js but i am getting this error 
![image](https://user-images.githubusercontent.com/99251572/230601322-4610c712-b9dc-4256-99ec-9ca8971ca52a.png)
![image](https://user-images.githubusercontent.com/99251572/230601377-bbeb3f65-b64b-44b5-80b7-c650622d86e0.png)

**Comment by StefaniaPozzi** [comment]
It's an issue of ethers v6 library. You have to downgrade it to v5. Good luck!

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
