### ISSUE TITLE
Error HH16: The directory C:\Users\PC contains files that could conflict:

### ISSUE THREAD

**Issue by Maakai123** [PatrickAlphaC/hardhat-fund-me-fcc#30]
I tried creating a new project with advanced sample project and i got the below error:

can some one tell me how to resolve this?

Welcome to Hardhat v2.9.9

√ What do you want to do? · Create an advanced sample project
√ Hardhat project root: · C:\Users\PC
√ Do you want to add a .gitignore? (Y/n) · y
Error HH16: The directory C:\Users\PC contains files that could conflict:

  contracts
  scripts
  test

Either try using a new directory, or remove the files listed above.

**Comment by PatrickAlphaC** [comment]
Could you please ask in the full repo? Thank you!

https://github.com/smartcontractkit/full-blockchain-solidity-course-js
