### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by yigtkaya** [PatrickAlphaC/hardhat-fund-me-fcc#56]
Hi everythink. is working fine till we add 

!developmentChains.includes(network.name)
    ? describe.skip
    :

into tests, I'm getting error:
TypeError: Cannot read properties of undefined (reading 'includes')

I couldn't figure out what to do anybody can help ?

https://github.com/yigtkaya/hardhat-fund-me (own github link for course code)

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

Thank you!

**Comment by RomeDomeYome** [comment]
im also getting this error
