### ISSUE TITLE
I copied the code but it still doesn't work

### ISSUE THREAD

**Issue by wangyangv1** [PatrickAlphaC/hardhat-fund-me-fcc#69]
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/49341812/186340202-7bf23c66-9eff-405f-a5cc-395a6612e223.png">

**Comment by jamaltheatlantean** [comment]
Can you just paste your deploy script so people can see it instead?
saying you copied the code isn't really helpful for you or anyone trying to help you out.

**Comment by wangyangv1** [comment]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/49341812/186879151-55965609-179e-4ace-8c39-a88e227b0487.png">


> Can you just paste your deploy script so people can see it instead? saying you copied the code isn't really helpful for you or anyone trying to help you out.

always encounter unexpected problems
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/49341812/186879326-73b476c7-7140-40d8-9796-a8755b027750.png">

**Comment by wangyangv1** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/49341812/186881585-c4439dc6-2b42-46af-a432-181d44add76b.png">
Are these due to package version mismatches? This is giving me a huge headache

**Comment by wangyangv1** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/49341812/186884759-4003b252-02ba-4aa2-b16a-25938d3d74c5.png">
I code exactly what the class says, but there are so many bad problems

**Comment by jamaltheatlantean** [comment]
I''l start with the last one, HH303 is an error from hardhat. You do not have a deploy task downloaded. Do npm hardhat install -D hardhat-deploy || or yarn if that's what you use.

**Comment by jamaltheatlantean** [comment]
As for the rest i'll start by saying i use javascript and not typescript so i don't know if its from the mix of package version, but you're still not showing the error message you're getting. I could only address the last frame because i saw the error message.

**Comment by wangyangv1** [comment]
> As for the rest i'll start by saying i use javascript and not typescript so i don't know if its from the mix of package version, but you're still not showing the error message you're getting. I could only address the last frame because i saw the error message.

Thank you, have you finished this tutorial? I followed the steps of the video exactly, but I keep failing, the first few tasks I have done well

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
